name: "[Balancer] build image from fork"

on: 
  pull_request:
    branches: [main, develop]

jobs:
  build_from_fork:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./balancer
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.PERSONAL_ACCESS_TOKEN_GITHUB}}

      - name: buildx image
        run: |
          docker build . --tag new_balancer_image
      
